project:
  type: book
  output-dir: docs

book:
  title: "Deep Learning Notes"
  author: "TheG3ntleman"
  date: "3/11/2023"
  chapters:
    - index.qmd
    - references.qmd
  navbar:  false
    # search: true
  sidebar: 
     title: false
     search: false

bibliography: references.bib

format:
  html:
    theme: solar
  pdf:
    documentclass: scrreprt



