project:
  type: book
  output-dir: docs

html:
  mainfont: Times New Roman

book:
  title: "Deep Learning Notes"
  author: "TheG3ntleman"

  search: false
  page-navigation: false
  sidebar: 
    title: false


  chapters:      
  - index.qmd
  - part: artificial-neuron.qmd
    chapters:
      - mcculloch-pitts-neuron.qmd
  - references.qmd


bibliography: references.bib

format:
  html:
    theme: solar
  pdf:
    documentclass: scrreprt



