project:
  type: book
  output-dir: docs

book:
  title: "Deep Learning Notes"
  author: "TheG3ntleman"

  search: false
  page-navigation: false
  sidebar: 
    title: false

  chapters:      
  - index.qmd
  - part: artificial-neuron/artificial-neuron.qmd
    chapters:
      - artificial-neuron/mcculloch-pitts-neuron.qmd
      - artificial-neuron/perceptron.qmd
  - part: mathematics/mathematics.qmd
    chapters:
      - mathematics/boolean-logic.qmd
  - references.qmd


bibliography: references.bib

format:
  html:
    theme: litera
    mainfont: Georgia, serif;
  pdf:
    documentclass: scrreprt



