# The machine learning setup
The machine learning setup is a framwork that allows us to analyze machine learning problems in a structured way. Every machine learning problem constitutes of:
1. The underlying data
2. A suitable parametric model
3. A loss/objective/error functions
4. A learning mechanism by which the loss function is minimized.

### The data
A solution to any machine learning problems starts by looking at the data involved. 

write seperate sections about: data augmentation, data cleaning/pre-processing, ...

### The model
Every machine learning model is based of a real-world phenomenon. Therefore, it seems that there exists some mysterious function that governs that particular phenomenon, even through the function itself is not apparant. Using machine learning models we try to fit this function by observing it behaviour through the data. A model suitable to the type of data greatly simplifies the problem and leads to better results.

### The loss functions
We must a mechanism by which we can gauge the performance of the model. This is done with the help of a loss function. As above, depending on the problem a poor selection for the loss function will lead to problems. 

### The learning mechanism
A mechanism by which we can adjust the parameters of the model to minimize the loss function is necessary to fit our model to the ideal function.

## A Discussion on model convergence
The precise definition of convergence of a model varies depending on the context. However, in general we say that a model has converged if we have roughly reached a set of parameters at which the loss function has a minima. It is not necessary that the minimum loss is 0, it is a luxury.